Add .uname section to with kernel version to EFI
Based on mkinitcpio and ukify.

diff --git a/efi-mkuki b/efi-mkuki
--- a/efi-mkuki
+++ b/efi-mkuki
@@ -1,7 +1,7 @@
 #!/bin/sh
 # vim: set ts=4:
 #---help---
-# Usage: efi-mkuki [options] <vmlinuz> [<microcode>...] [<initrd>]
+# Usage: efi-mkuki [options] -k <kver> <vmlinuz> [<microcode>...] [<initrd>]
 #        efi-mkuki <-h | -V>
 #
 # Create an EFI Unified Kernel Image (UKI) - a single EFI PE executable
@@ -16,6 +16,10 @@
 # Options:
 #   -c <cmdline | file>  Kernel cmdline, or location of file with kernel cmdline
 #                        (if begins with "/" or "."). Defaults to /proc/cmdline.
+#
+#   -k <version | file>  Kernel release ("uname -r" information), or location of
+#                        file with kernel release (if begins with "/" or ".").
+#                        This option is REQUIRED.
 #
 #   -o <file>            Write output into <file>. Defaults to <vmlinuz>.efi.
 #
@@ -70,10 +74,12 @@ output=
 osrel=/etc/os-release
 splash=
 efistub=
+kver=
 
-while getopts ':c:o:r:s:S:hV' OPT; do
+while getopts ':c:k:o:r:s:S:hV' OPT; do
 	case "$OPT" in
 		c) cmdline=$OPTARG;;
+		k) kver=$OPTARG;;
 		o) output=$OPTARG;;
 		r) osrel=$OPTARG;;
 		s) splash=$OPTARG;;
@@ -86,6 +92,7 @@ done
 shift $((OPTIND - 1))
 
 [ $# -ge 1 ] || die "invalid number of arguments, see '$PROGNAME -h'"
+[ "$kver" ] || die 'missing required option -k'
 
 if ! [ "$efistub" ]; then
 	case "$(uname -m)" in
@@ -107,6 +114,15 @@ case "$cmdline" in
 	*) printf '%s\n' "$cmdline" > "$tmpdir"/cmdline;;
 esac
 cmdline="$tmpdir/cmdline"
+
+uname="$tmpdir/uname"
+case "$kver" in
+	/* | .*) head -n 1 "$kver";;
+	*) printf '%s\n' "$kver";;
+esac > "$uname"
+
+grep -q '^[0-9]\+\.[0-9][0-9A-Za-z_.-]*$' "$uname" \
+	|| die "invalid kernel version (-k): $(cat "$uname")"
 
 linux=$1; shift
 
@@ -130,7 +146,7 @@ test "$offset" -eq "$offset" 2>/dev/null \
 offset="$(next_offset 0 "$offset")"  # align offset
 
 objcopy_opts=''
-for section in osrel cmdline splash linux initrd; do
+for section in uname osrel cmdline splash linux initrd; do
 	filename="$(getval "$section")"
 	[ "$filename" ] || continue
 
